# Yaml code for creating a deployment and service of episode 1 backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Auth-deployment
  labels:
    app: Auth

spec:
  replicas: 2
  selector:
    matchLabels:
      app: Auth
  
  template:
    metadata:
      labels:
        app: Auth
    spec:
      # this is the specification of pods
      containers:
        - name: containerAuthentication1
          image: muqeem/Auth:latest
          ports:
           - containerPort: 4000
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service/scdfinalexam"
            - name: EVENT_SERVICE
              value: "external service of event event microservice deployment"

---
# Yaml for making the external service for Auth deployment

apiVersion: v1
kind: Service
metadata:
  name: Auth-service

spec:
  type: NodePort
  selector:
    app: Auth

  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 32010
