# Yaml code for creating a deployment and service of episode 1 backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Classrooms-deployment
  labels:
    app: Classrooms

spec:
  replicas: 2
  selector:
    matchLabels:
      app: Classrooms
  
  template:
    metadata:
      labels:
        app: Classrooms
    spec:
      # this is the specification of pods
      containers:
        - name: containerClassrooms
          image: muqeem/Classrooms:latest
          ports:
           - containerPort: 4001
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service/scdfinalexam"
            - name: EVENT_SERVICE
              value: "external service of event event microservice deployment"

---
# Yaml for making the external service for Classrooms deployment

apiVersion: v1
kind: Service
metadata:
  name: Classrooms-service

spec:
  type: NodePort
  selector:
    app: Classrooms

  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 32011
