# Yaml code for creating a deployment and service of episode 1 frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # this is the specification of pods
      containers:
        - name: containerfront
          image: muqeem/frontend1:latest
          ports:
           - containerPort: 3000
          env:
            - name: EVENT_POST
              value: "http://ip172-18-0-43-cp3piei8dsgg00dlotog.direct.labs.play-with-k8s.com:32012"
            - name: EVENT_AUTH
              value: "http://ip172-18-0-43-cp3piei8dsgg00dlotog.direct.labs.play-with-k8s.com:32010"
            - name: EVENT_CLASSROOM
              value: "http://ip172-18-0-43-cp3piei8dsgg00dlotog.direct.labs.play-with-k8s.com:32011"

---
# Yaml for making the external service for frontend1 deployment

apiVersion: v1
kind: Service
metadata:
  name: frontend1-service

spec:
  type: NodePort
  selector:
    app: frontend1

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32011
